### ISSUE TITLE
Suggestions: Reset + tooltip

### ISSUE THREAD

**Issue by Ithronyar** [Lemonszz/BetterCompass#1]
It would be useful if custom-set compasses could be reset to point back at the player's spawn point. Could be as simple as right-clicking air, or maybe crafting the compass with nothing and getting a "clean" compass in the crafting output.

Also, maybe a "Custom Target" tooltip on compasses with player-set locations? Sometimes it can be hard to tell which ones point to a spawn point, and which ones point to a player-set location.

**Comment by Lemonszz** [comment]
Good ideas.

I'll add a reset recipe in the next update and I'll look into ways to distinguish custom locations.

**Comment by Lemonszz** [comment]
This has been implemented as of version 1.2.0 
https://minecraft.curseforge.com/projects/better-compass/files/2535562
