### ISSUE TITLE
No 1.14.4 download on CurseForge

### ISSUE THREAD

**Issue by Slasherss1** [Lemonszz/BetterCompass#10]
There are only files for 1.13.2 and 1.12.2, both for forge.

**Comment by Shnupbups** [comment]
If you're looking for the Fabric 1.14.4 version, you can find that on [CurseForge here](https://www.curseforge.com/minecraft/mc-mods/better-compass-fabric) and on [GitHub here](https://github.com/Lemonszz/better-compass-fabric).

As for a Forge 1.14.4 version, I don't believe one has been released.
