### ISSUE TITLE
Support for Quark's "Compasses Everywhere" Feature

### ISSUE THREAD

**Issue by stohun01** [Lemonszz/BetterCompass#2]
Quark adds the following feature:
> - In the Nether, a compass will point to the portal you entered from, provided you had it on you when you did.
> - In the End, a compass will point to the overworld portal.

With both Quark and Better Compass installed the compass needle in the nether goes crazy. I suggest having clean compasses that have no custom location be able to use the quark feature and also allow setting locations in the nether (useful for land-marking fortresses). And when a compass has a custom location in a dimension other than the one you're in the needle could continually spin in circles.

**Comment by Lemonszz** [comment]
I've added support for this in V1.3.0 via a config option.

In the end, they wont point to the portal, but you can set it anyway so it's not a big deal ¯\\\_(ツ)_/¯

I'd recommend turning off Quark's compass tweaks, as they wont do anything anyway
https://minecraft.curseforge.com/projects/better-compass/files/2535758

**Comment by stohun01** [comment]
Thanks, it works great.
