### ISSUE TITLE
Add shift+ modifier to set compass.

### ISSUE THREAD

**Issue by wendall911** [Lemonszz/BetterCompass#4]
It is hard to use the compass if you only need to right click. If wandering around and using your compass, it is super easy to accidentally reset it. It would be much better if the handler only accepted input for shift+right click to set the compass. As-is, it works very well, just needs to have a way to not so trivially reset to a new point.

**Comment by Lemonszz** [comment]
Thanks for the suggestion. 

I agree, I'll add this as an option in the next update.

**Comment by wendall911** [comment]
Thanks looking forward to it. :+1:
