### ISSUE TITLE
Crash in 1.14 Pre-release 2

### ISSUE THREAD

**Issue by ScottoMotto** [Lemonszz/BetterCompass#8]
https://paste.ee/p/roBeR
Better Compass loads ok but crashes on use.

**Comment by Lemonszz** [comment]
The fabric version isnt up to date with the latest snapshots.

**Comment by ScottoMotto** [comment]
I don't mean to be daft but where do I get a newer version? I just downloaded all of this today. http://fabric.asie.pl/use/ and newest at CurseForge.

**Comment by ScottoMotto** [comment]
It still crashes upon use in Prerelease 1: https://paste.ee/p/ECCdz

**Comment by Lemonszz** [comment]
There isn't a newer version. I'm not currently supporting my Fabric mods.

**Comment by ScottoMotto** [comment]
Then please remove them from Curseforge.

**Comment by Lemonszz** [comment]
no

**Comment by ScottoMotto** [comment]
I'm not trying to tell you what you should do with your own mods. I read it again and comes off like that. Sorry if it was offensive.
The point I am trying to make is that mods targeting particular snapshots are worthless. Literally no one will ever use those snapshots again once they are superseded. This may be a weakness in the fabric system with supporting the most cutting edge releases.
I hope you will reconsider and release a newer build because the mod is very nice for play without a minimap. You seem to be very proficient in updating mods.
